apiVersion: v1
kind: Pod
metadata:
  name: squid
  labels:
    name: squid
spec:
  containers:
    - name: squid
      image: sameersbn/squid
      ports:
        - containerPort: 3128
          protocol: TCP
