apiVersion: v1
kind: Pod
metadata:
  name: squid
  labels:
    name: squid
spec:
  containers:
    - name: squid
      image: quay.io/sameersbn/squid:3.3.8-3
      ports:
        - containerPort: 3128
          protocol: TCP
